# Data Wrangling

Crash course into data generation, handling, manipulation, transformatio and preparation. This can lead to further analysis: statistical or visual (which we will explore in workshop 3) or training of predictive models. This assumes the data is already cleaned and structured, not in raw form (which we will briefly explore in workshop 4).

Pre-requisites: basic understanding of programming, Python is a plus.

### Table of contents

- [Numpy Arrays](#Numpy-Arrays)
 - [Creation](#Creation)
   - Shape
   - Data Type
   - Generation
   - Copying
   - [Randomness](#Randomness)
 - [Accessing](#Accessing)
 - [Operations](#Array-Operations)
   - [Broadcasting](#Broadcasting)



- [Pandas Dataframes](#Pandas-Dataframes)
 - Creation
 - accessing
 - extension
 - missing values
 - deletion
 - operations
 - aggregation
 - loading and saving


- Further reading

TODO: sectioning and links

TODO: exercises

## Numpy Arrays

Numpy offers powerful array objects. It is part of the de-facto [Python ecosystem](https://www.scipy.org) for mathematics, science and engineering, and sits at the foundation of most scientific computation libraries.

They are homogenous (all elements are the same type) containers, usually for numbers, that indexed by integers. They are similar to lists but offer much more functionality and performance.

In [2]:
import numpy as np  # import the package into our namespace, under the usual name `np`

### Array Creation

Create an array from a regular `list`s object:

In [125]:
squares = np.array([0, 1, 4, 9, 16, 25, 36, 49])

Create a 2D array/a matrix:

In [95]:
m = np.array([
    [5, 2, 3],
    [4, 5, 1],
    [7, 1, 2],
    [6, 2, 9],
])

Arbitrarily many dimensions dimensions:

In [19]:
# pixels, which are 3-dimensional points:
R = [1, 0, 0]  # red
B = [0, 0, 1]  # blue
W = [1, 1, 1]  # white

In [284]:
image = np.array([
    [B, B, R, R],
    [B, B, W, W],
    [R, R, R, R],
    [W, W, W, W],
    [R, R, R, R],
    [W, W, W, W],
])

In [285]:
image

array([[[0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

#### Array Shape

The _shape_ of each array is the size of each dimension:

In [126]:
squares.shape  # 8 elements

(8,)

In [97]:
m.shape  # 4 rows, 3 columns

(4, 3)

In [99]:
picture.shape  # 6 rows, 4 columns, each element containing 3 coordinates

(6, 4, 3)

An array's _rank_ is the number of dimensions.

---

All dimensions must have equal size, meaning we can't have something like:

In [102]:
a = np.array([
    [1,2,3], 
    [1,2]
])
a

array([list([1, 2, 3]), list([1, 2])], dtype=object)

In [103]:
a.shape

(2,)

It just interpreted it as an array of two elements, each element being a list. More details in the next sub-section.

#### Array Data Types

An array's data type is the type of the object they are holding.

In [104]:
squares.dtype

dtype('int64')

In [105]:
m.dtype

dtype('int64')

In [106]:
np.array([1.5, 2.3, 4.9]).dtype

dtype('float64')

In [107]:
np.array([True, True, False]).dtype

dtype('bool')

In [108]:
np.array(['abc', 'def', 'xy']).dtype  # unicode with 3 or fewer characters

dtype('<U3')

Compatible datatypes are "up-scaled":

In [112]:
a = np.array([True, 5])
a

array([1, 5])

In [113]:
a.dtype

dtype('int64')

In [109]:
np.array([1, 2.5]).dtype

dtype('float64')

In [114]:
np.array([True, 2, 3.5]).dtype

dtype('float64')

In [120]:
np.array([7, 'abc']).dtype  # calls `str` on them

dtype('<U21')

Incompatible datatypes are put under the `object` umbrella:

In [122]:
s = {1, 2, 3}
np.array([s, 5]).dtype

dtype('O')

You can also call type conversion manually:

In [123]:
np.array([2, 4, 0]).astype(bool)

array([ True,  True, False])

In [124]:
np.array([2, 4, 0]).astype(float)

array([2., 4., 0.])

Or upon creation:

In [135]:
np.array([2, 4], dtype=float)

array([2., 4.])

#### Array Generation

Similar to the built-in `range`, generate an array of sequential numbers:

In [134]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

**ℹ️ Tip**: it's called `a range` as in `an interval`, not `arrange` as in `align` — it confused me for the longest time.

A more powerful, non-integer counterpart:

In [138]:
np.linspace(start=0, stop=15, num=5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

Similarly, there is a logarithmic counterpart:

In [208]:
np.logspace(0, 3, num=4, base=10.)

array([   1.,   10.,  100., 1000.])

---

Generate an array of equal elements:

In [31]:
np.ones(4)

array([1., 1., 1., 1.])

In [140]:
np.zeros((3, 2))  # any shape

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Specify shape based on another array's:

In [142]:
np.zeros_like(squares)  # same shape and dtype as `squares`

array([0, 0, 0, 0, 0, 0, 0, 0])

If you just want to instantiate an array, filling the elements later, you skip the filling step, and create one with bogus elements:

In [173]:
np.empty(50)  # the address where it is assigned is arbitrary, so you will likely see different results each time this is ran

array([2.68156159e+154, 2.68156159e+154, 1.23516411e-322, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.22205724e-314, 0.00000000e+000, 2.22194593e-314,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 3.47667790e-308])

#### Array Copying

Assign a new "label" to the same array object (similar to `&` references in C-like languages):

In [145]:
a = np.ones(3)  # create an array, and "assign the label" `a` to it
a

array([1., 1., 1.])

In [148]:
b = a  # `b` is now another label for the same array

array([5., 1., 1.])

Modifications in any label affect the base object:

In [151]:
b[0] = 5
b

array([5., 1., 1.])

In [152]:
a  # modified indirectly

array([5., 1., 1.])

---

To "clone" the object, use `copy` instead:

In [155]:
a = np.ones(3)
a

array([1., 1., 1.])

In [154]:
b = np.copy(a)

In [156]:
b[0] = 5
b

array([5., 1., 1.])

In [157]:
a

array([1., 1., 1.])

**ℹ️ Tip**: this still fails if you store non-primitive data types:

In [162]:
a = np.array([
    {1, 2, 3},  # a set
    {5, 4},
])
a

array([{1, 2, 3}, {4, 5}], dtype=object)

In [163]:
b = np.copy(a)

In [164]:
b[0].remove(3)
b

array([{1, 2}, {4, 5}], dtype=object)

In [165]:
a  # still affected

array([{1, 2}, {4, 5}], dtype=object)

In this case, `deepcopy` would be useful, from the [copy built-in library](https://docs.python.org/3.7/library/copy.html).

#### Randomness

Generating random numbers sees more use in training predictive models, but they can also be relevant in terms of example data. It also has some uses in some advanced data visualizations.

Uniformly distributed $V \sim U(0, 1)$:

In [175]:
np.random.rand(4, 2)

array([[0.8263408 , 0.60306013],
       [0.54506801, 0.34276383],
       [0.30412079, 0.41702221],
       [0.68130077, 0.87545684]])

Normal standard distribution, zero-centered and unit deviation $\sim N(0, 1)$:

In [174]:
np.random.randn(3)

array([-0.8667404 , -0.92662298,  0.27574741])

Uniformly distributed integers in an interval $V \sim U_{\mathbb{Z}}(a, b)$:

In [41]:
np.random.randint(0, 10, size=3)

array([3, 4, 0])

Sampling elements from a given set, with or without replcement:

In [42]:
np.random.choice(['red', 'green', 'blue'], size=5)

array(['red', 'red', 'green', 'blue', 'red'], dtype='<U5')

Generating permutations $\sigma \in \mathbb{N}_n$:

In [43]:
np.random.permutation([4, 2, 1])

array([2, 4, 1])

**ℹ️ Tip**: setting the random seed allows for reproducibility of results when randomness is involved. The results are still random, but they are the same ones, every time. Since most scientific libraries delegate their random generation to numpy, `np.random.seed(123)` is sufficient for all. Read more about [random number generation](https://en.wikipedia.org/wiki/Pseudorandom_number_generator).

### Array Accessing

Index, and slice accessing is similar to `list`s:

In [177]:
squares  # to remember what it contains

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [178]:
squares[2]  # remember, zero-indexed

4

In [186]:
squares[2:6]  # slices

array([ 4,  9, 16, 25])

---

It extends naturally to multi-dimensional arrays:

In [180]:
m  # to remember what it contains

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [181]:
m[:2]  # first two rows

array([[5, 2, 3],
       [4, 5, 1]])

In [182]:
m[:, :2]  # all rows, first two columns

array([[5, 2],
       [4, 5],
       [7, 1],
       [6, 2]])

In [183]:
m[:2, :2]  # first two rows of the first two columns

array([[5, 2],
       [4, 5]])

---

_Fancy_ indexing (this is the actual term) allows for accessing multiple elements at once:

In [194]:
indices = [4, 2, 2]  # can also repeat
squares[indices]

array([16,  4,  4])

In [200]:
row_indices = [0, 1]
col_indices = [0, 2]
m[row_indices, col_indices]

array([5, 1])

### Array Iteration

Iteration works the same:

In [201]:
for sq in squares:
    print(sq)

0
1
4
9
16
25
36
49


Enumeration has its n-dimensional counterpart:

In [203]:
for index, element in np.ndenumerate(m):
    print('index', index, 'element', element)

index (0, 0) element 5
index (0, 1) element 2
index (0, 2) element 3
index (1, 0) element 4
index (1, 1) element 5
index (1, 2) element 1
index (2, 0) element 7
index (2, 1) element 1
index (2, 2) element 2
index (3, 0) element 6
index (3, 1) element 2
index (3, 2) element 9


### Array Operations

Arithmetic operations are _vectorized_ — extended for array operations:

In [210]:
squares  # to remember what it contains

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [211]:
squares + 100  # add 100 to each element

array([100, 101, 104, 109, 116, 125, 136, 149])

In [216]:
squares ** .5  # raise every element to the power 0.5 (square root it)

array([0., 1., 2., 3., 4., 5., 6., 7.])

**ℹ️ Tip**: an array containing all `5`s is generated by `np.ones(dim) * 5`

---

Conditional operators as well, and their result is boolean:

In [217]:
squares > 5

array([False, False, False,  True,  True,  True,  True,  True])

In [218]:
squares == 1

array([False,  True, False, False, False, False, False, False])

In [220]:
odd = (squares % 2 == 0)
odd

array([ True, False,  True, False,  True, False,  True, False])

---

There are also unary operators, such as negation:

In [223]:
~odd

array([False,  True, False,  True, False,  True, False,  True])

In [224]:
-squares

array([  0,  -1,  -4,  -9, -16, -25, -36, -49])

---

Aggregations and other more complex operations are available as methods:

In [225]:
squares.sum()  # sum of all elements

140

In [226]:
sum(squares)  # equivalent

140

In [331]:
np.log(squares + 1)

array([0.        , 0.69314718, 1.60943791, 2.30258509, 2.83321334,
       3.25809654, 3.61091791, 3.91202301])

In [227]:
squares.mean()  # equivalent to sum/len

17.5

In [229]:
squares.std()  # standard deviation

16.680827317612277

In [230]:
squares.cumsum()  # cumulative sum

array([  0,   1,   5,  14,  30,  55,  91, 140])

---

In [249]:
a = np.array([2, 0, 4])

In [251]:
a.argmin()  # the index of the minimum element

1

In [250]:
a.argsort()  # the indices that would sort the array

array([1, 0, 2])

---

Operators naturally extend to multiple dimensions as well:

In [12]:
m * 10

array([[50, 20, 30],
       [40, 50, 10],
       [70, 10, 20],
       [60, 20, 90]])

In [221]:
m == 5

array([[ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

Element-wise application of operators between to arrays:

In [252]:
a

array([2, 0, 4])

In [253]:
b = np.array([9, 6, 6])

In [254]:
a + b

array([11,  6, 10])

In [255]:
a * b

array([18,  0, 24])

---

Binary operations:

In [322]:
a = squares > 5
a

array([False, False, False,  True,  True,  True,  True,  True])

In [325]:
b = (squares % 2 == 0)
b

array([ True, False,  True, False,  True, False,  True, False])

In [327]:
a & b

array([False, False, False, False,  True, False,  True, False])

In [328]:
a | b

array([ True, False,  True,  True,  True,  True,  True,  True])

---

In [270]:
x = np.linspace(0, np.pi, num=5)
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [272]:
np.sin(x).round(3)

array([0.   , 0.707, 1.   , 0.707, 0.   ])

---

Functions, when applied to multi-dimensional arrays, allow you to specify an axis. In a 2D matrix, that means either column-wise or row-wise:

In [273]:
m  # refresher

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [275]:
m.sum()  # overall sum of all elements, no axis specified

47

In [277]:
m.sum(axis=0)  # first axis, column wise — one result for each column

array([22, 10, 15])

In [278]:
m.sum(axis=1)  # per each row

array([10, 10, 10, 17])

---

The `*` operator gives the hadamard product (element-wise multiplication) between matrices:

In [279]:
m * m

array([[25,  4,  9],
       [16, 25,  1],
       [49,  1,  4],
       [36,  4, 81]])

Matrix multiplication is done using the `@` operator (previously, using `a.dot(b)`):

In [282]:
m @ m.transpose()

array([[ 38,  33,  43,  61],
       [ 33,  42,  35,  43],
       [ 43,  35,  54,  62],
       [ 61,  43,  62, 121]])

---

**💪 Exercise**: re-generate the `squares` array, but using numpy:

In [214]:
n = len(squares)
np.arange(n) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49])

#### Reshaping

Arrays can be morph into a different (compatible) shape:

In [127]:
squares  # original

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [128]:
squares.reshape(2, 4)  # 2 rows, 4 columns

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [130]:
squares.reshape(4, 2)  # 4 rows, 2 columns

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49]])

Flatten an array of any shape with `.reshape(-1)`:

In [131]:
m.reshape(-1)

array([5, 2, 3, 4, 5, 1, 7, 1, 2, 6, 2, 9])

In [132]:
picture.reshape(-1).shape

(72,)

Transposition (axis inversion):

In [231]:
m.T

array([[5, 4, 7, 6],
       [2, 5, 1, 2],
       [3, 1, 2, 9]])

---

Generating new axes can be useful when certain functions require the data in a particular shape, even if it is degenerated:

In [233]:
squares[:, np.newaxis]  # make each element be a list

array([[ 0],
       [ 1],
       [ 4],
       [ 9],
       [16],
       [25],
       [36],
       [49]])

In [232]:
squares[np.newaxis, :]  # wrap the array

array([[ 0,  1,  4,  9, 16, 25, 36, 49]])

In [235]:
squares.shape  # original shape

(8,)

In [234]:
squares[:, np.newaxis].shape

(8, 1)

In [236]:
squares[np.newaxis, :].shape

(1, 8)

**ℹ️ Tip**: shapes are simply "views" of the underlying data, which is stored the same way, regardless of assigned shape. Read more about how [data is stored internally](https://docs.scipy.org/doc/numpy-1.13.0/reference/internals.html).

**💪 Exercise**: in how many ways can an array of size 12 be reshaped?

In [319]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [320]:
a.shape

(12,)

In [317]:
a.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [315]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [314]:
a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [313]:
a.reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [318]:
a.reshape(12, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

**👾 Trivia**: [this is why](https://www.youtube.com/watch?v=U6xJfP7-HCc) a base-12 number system would make arithmetic easier.

### Broadcasting

The same operation, `+`, is used both when adding a constant to each element, and also when performing element-wise addition. This concept is extended to arbitrarily many dimensions. The right-hand-side of the operator is _broadcasted_ until it reaches the left-hand-side's shape.

In [288]:
squares + 10

array([10, 11, 14, 19, 26, 35, 46, 59])

In [290]:
tens = [10] * 8  # eight elements, each equal to 10
squares + tens  # behind the scenes, the rhs is broadcasted to match the lhs' shape

array([10, 11, 14, 19, 26, 35, 46, 59])

It becomes non-arbitrary in higher dimensions:

In [292]:
m  # content refresher

array([[5, 2, 3],
       [4, 5, 1],
       [7, 1, 2],
       [6, 2, 9]])

In [293]:
m + [100, 10, 0]  # add these values to each row
# for each row, the first element 

array([[105,  12,   3],
       [104,  15,   1],
       [107,  11,   2],
       [106,  12,   9]])

In [295]:
m + [[1000], [100], [10], [0]]  # add these values to each column
# 

array([[1005, 1002, 1003],
       [ 104,  105,  101],
       [  17,   11,   12],
       [   6,    2,    9]])

Read more about [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html).

### Array Masking

Boolean indexing — access only those elements where the indexing array is `True`:

In [7]:
mask = (squares > 5)

In [8]:
mask

array([False, False, False,  True,  True,  True,  True])

In [9]:
squares[mask]

array([ 9, 16, 25, 36])

### Array Extension

Since `+` is reserved for addition, array concatenation is done by function:

In [298]:
np.concatenate([squares, squares])

array([ 0,  1,  4,  9, 16, 25, 36, 49,  0,  1,  4,  9, 16, 25, 36, 49])

In the multi-dimensional case:

In [300]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [302]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [303]:
np.concatenate([a, b])

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [1., 1.],
       [1., 1.]])

---

In [309]:
c = np.zeros((2, 2))

In [310]:
np.vstack([b, c])  # on top of eachother

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [311]:
np.hstack([b, c])  # next to eachother

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

## Pandas Dataframes

Dataframes are easy-to-use, functionality-packed data structures for data handling and analysis. They can be thought of as non-homogenous matrices  for row/column labeled data, which also offer a lot of extra functionality.

In [44]:
import pandas as pd  # the usual abbreviation

### Creation

When instantiating from scratch, specify the values of each column (usually the same length):

In [493]:
students = pd.DataFrame({
    'height':    np.random.randint(150, 200, size=5),
    'weight':    np.random.randint(50,  100, size=5),
    'graduated': np.random.random(size=5) > .5,  # same as np.random.randint(0, 1, size=10).astype(bool)
})

Each row is an observation (i.e.: a student), each column is a variable (i.e.: a measurement):

In [494]:
students

height  weight  graduated
0     158      51       True
1     182      57       True
2     175      56      False
3     185      85       True
4     153      83       True

_Note_: since randomness is involved, when you run this notebook, you'll likely see different results.

Dataframes are implicitly indexed by integers, but rows can be assigned more descriptive indices:

In [495]:
students.index = list('abcde')

In [496]:
students

height  weight  graduated
a     158      51       True
b     182      57       True
c     175      56      False
d     185      85       True
e     153      83       True

### Properties

Shape and data type are extended to dataframes as well:

In [497]:
len(students)  # size of first dimension, i.e.: number of rows

5

In [498]:
students.shape

(5, 3)

In [499]:
students.dtypes

height       int64
weight       int64
graduated     bool
dtype: object

In [500]:
students.height.astype(float)

a    158.0
b    182.0
c    175.0
d    185.0
e    153.0
Name: height, dtype: float64

### Accessing

Access rows elements by index:

In [501]:
students.loc['a']  # the observations for student A

height        158
weight         51
graduated    True
Name: a, dtype: object

Access rows by their position, regardless of index name:

In [502]:
students.iloc[0]

height        158
weight         51
graduated    True
Name: a, dtype: object

Slices are extended row-wise:

In [503]:
students[:3]

height  weight  graduated
a     158      51       True
b     182      57       True
c     175      56      False

---

Access a specific column:

In [504]:
students.graduated  # we can also access column-wise

a     True
b     True
c    False
d     True
e     True
Name: graduated, dtype: bool

Access multiple columns at once:

In [505]:
columns = ['weight', 'height']
students[columns]

weight  height
a      51     158
b      57     182
c      56     175
d      85     185
e      83     153

Masking is performed row-wise by providing a boolean array with the same length as the number of rows:

In [506]:
students[students.graduated]

height  weight  graduated
a     158      51       True
b     182      57       True
d     185      85       True
e     153      83       True

---

Randomly sample rows:

In [507]:
students.sample(3)

height  weight  graduated
c     175      56      False
e     153      83       True
d     185      85       True

In [508]:
students.sample(frac=.5)  # half of all rows

height  weight  graduated
c     175      56      False
b     182      57       True

In [509]:
len(students)

5

---

Iterating over the dataframe defaults to going over its columns:

In [510]:
for column in students:
    print(column)

height
weight
graduated


`iterrows()` is used to iterate over each row:

In [511]:
for student, row in students.iterrows():
    print(student, row.height, row.weight)

a 158 51
b 182 57
c 175 56
d 185 85
e 153 83


**💪 Exercise**: select rows for students yet to graduate

In [512]:
students[~students.graduated]

height  weight  graduated
c     175      56      False

### Extending

To add a new row, just specify it's index (`loc`) or positional index (`iloc`):

In [513]:
students.loc['x'] = (170, 70, True)  # specify the value for each column

In [514]:
students

height  weight  graduated
a     158      51       True
b     182      57       True
c     175      56      False
d     185      85       True
e     153      83       True
x     170      70       True

**ℹ️ Tip**: even though `df.iloc[len(df) - 1] = ...` can be used to append at the end of any dataframe, this is not recommended. If you wish to create a dataframe iteratively, instead of appending each element, store them in a different container and convert the data to a dataframe at the end. This is also the reason why there is no `append` function for dataframes.

To add a new column, assign it directly to the dataframe:

In [515]:
students['age'] = np.random.randint(18, 24, size=6)  # adding a new column

In [516]:
students

height  weight  graduated  age
a     158      51       True   21
b     182      57       True   19
c     175      56      False   22
d     185      85       True   23
e     153      83       True   18
x     170      70       True   23

**ℹ️ Tip**: this syntax must be used for column creation. `df.column` only works for accessing existing columns.

Create a column based on another

In [517]:
students['can_ride'] = (students.height > 170)  # "you must be this tall to ride the roller coaster"

In [518]:
students

height  weight  graduated  age  can_ride
a     158      51       True   21     False
b     182      57       True   19      True
c     175      56      False   22      True
d     185      85       True   23      True
e     153      83       True   18     False
x     170      70       True   23     False

---

Add multiple new rows, from another dataframe:

In [519]:
new_students = pd.DataFrame({
    'height': [160, 180],
    'weight': [ 60,  80],
})

new_students

height  weight
0     160      60
1     180      80

In [520]:
students = pd.concat([students, new_students], sort=False)
students

height  weight graduated   age can_ride
a     158      51      True  21.0    False
b     182      57      True  19.0     True
c     175      56     False  22.0     True
d     185      85      True  23.0     True
e     153      83      True  18.0    False
x     170      70      True  23.0    False
0     160      60       NaN   NaN      NaN
1     180      80       NaN   NaN      NaN

_Note_ it's `pd.concat` but `np.concatenate`

Add multiple new columns, from another dataframe:

In [521]:
n_students = len(students)

new_info = pd.DataFrame({
    'fav_number':   np.random.randint(0, 100, size=n_students),
    'fav_icecream': np.random.choice(['vanilla', 'chocolate', 'strawberry'], size=n_students),
})

In [522]:
new_info.index = students.index  # set the same index, to make merging (and viewing) easier
new_info

fav_number fav_icecream
a          14    chocolate
b          78      vanilla
c          23   strawberry
d          62   strawberry
e          28      vanilla
x          80   strawberry
0          24    chocolate
1          15      vanilla

In [523]:
students = students.merge(new_info, left_index=True, right_index=True)
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51      True  21.0    False          14    chocolate
b     182      57      True  19.0     True          78      vanilla
c     175      56     False  22.0     True          23   strawberry
d     185      85      True  23.0     True          62   strawberry
e     153      83      True  18.0    False          28      vanilla
x     170      70      True  23.0    False          80   strawberry
0     160      60       NaN   NaN      NaN          24    chocolate
1     180      80       NaN   NaN      NaN          15      vanilla

### Missing Values

Since we only provided the `height` and `weight` measurements, for the new students, `nan` (not a number) is placed by default for the other columns:

In [524]:
students

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51      True  21.0    False          14    chocolate
b     182      57      True  19.0     True          78      vanilla
c     175      56     False  22.0     True          23   strawberry
d     185      85      True  23.0     True          62   strawberry
e     153      83      True  18.0    False          28      vanilla
x     170      70      True  23.0    False          80   strawberry
0     160      60       NaN   NaN      NaN          24    chocolate
1     180      80       NaN   NaN      NaN          15      vanilla

Missing value detection:

In [525]:
pd.isna(students)

height  weight  graduated    age  can_ride  fav_number  fav_icecream
a   False   False      False  False     False       False         False
b   False   False      False  False     False       False         False
c   False   False      False  False     False       False         False
d   False   False      False  False     False       False         False
e   False   False      False  False     False       False         False
x   False   False      False  False     False       False         False
0   False   False       True   True      True       False         False
1   False   False       True   True      True       False         False

Column-wise:

In [526]:
pd.isna(students.age)

a    False
b    False
c    False
d    False
e    False
x    False
0     True
1     True
Name: age, dtype: bool

The easiest method for handling missing data is dropping the observation alltogether:

In [527]:
students.dropna()

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51      True  21.0    False          14    chocolate
b     182      57      True  19.0     True          78      vanilla
c     175      56     False  22.0     True          23   strawberry
d     185      85      True  23.0     True          62   strawberry
e     153      83      True  18.0    False          28      vanilla
x     170      70      True  23.0    False          80   strawberry

Another method is filling it with some default value:

In [528]:
students.fillna({
    'graduated': False,
    'can_ride':  False,
    'age':       20,
})

height  weight  graduated   age  can_ride  fav_number fav_icecream
a     158      51       True  21.0     False          14    chocolate
b     182      57       True  19.0      True          78      vanilla
c     175      56      False  22.0      True          23   strawberry
d     185      85       True  23.0      True          62   strawberry
e     153      83       True  18.0     False          28      vanilla
x     170      70       True  23.0     False          80   strawberry
0     160      60      False  20.0     False          24    chocolate
1     180      80      False  20.0     False          15      vanilla

More methods for handling missing value will be explored in workshop 4.

**ℹ️ Tip**: the reason why we must use `pd.isna` to identify NANs, instead of `== np.nan` is because `np.nan` is a special element, which, by design, is not equal to anything, not even `np.nan`. Read more about [ternary logic](https://en.wikipedia.org/wiki/Three-valued_logic) and non-[finite numpy numbers](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.isfinite.html#numpy.isfinite).

### Deleting

Delete some columns:

In [575]:
students.drop(['weight', 'age'], axis=1)

height graduated can_ride  fav_number fav_icecream
a     158      True    False          14    chocolate
b     182      True     True          78      vanilla
c     175     False     True          23   strawberry
d     185      True     True          62   strawberry
e     153      True    False          28      vanilla
x     170      True    False          80   strawberry

Delete some rows, index-wise:

In [530]:
students.drop(['a', 'x'], axis=0)

height  weight graduated   age can_ride  fav_number fav_icecream
b     182      57      True  19.0     True          78      vanilla
c     175      56     False  22.0     True          23   strawberry
d     185      85      True  23.0     True          62   strawberry
e     153      83      True  18.0    False          28      vanilla
0     160      60       NaN   NaN      NaN          24    chocolate
1     180      80       NaN   NaN      NaN          15      vanilla

---

Deleting rows based on a boolean filtering is done by masking:

In [531]:
mask = (students.age > 21)  # filter underage ones
students[mask]

height  weight graduated   age can_ride  fav_number fav_icecream
c     175      56     False  22.0     True          23   strawberry
d     185      85      True  23.0     True          62   strawberry
x     170      70      True  23.0    False          80   strawberry

Dropping duplicate rows can be done using `drop_duplicate`, but since our dataframe contains no such rows, we will restrict it to duplicates on just the `can_ride` and `fav_icecream` columns:

In [532]:
students.drop_duplicates(subset=['can_ride', 'fav_icecream'], keep='first')

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51      True  21.0    False          14    chocolate
b     182      57      True  19.0     True          78      vanilla
c     175      56     False  22.0     True          23   strawberry
e     153      83      True  18.0    False          28      vanilla
x     170      70      True  23.0    False          80   strawberry
0     160      60       NaN   NaN      NaN          24    chocolate
1     180      80       NaN   NaN      NaN          15      vanilla

---

Deleting, much like any operation in the next subsection, does not operate _in place_. This means the `drop` function returns a new dataframe object, which is created by (deep) copying the original one and applying the operation on it. Writing your own functions in such a way helps with preventing unexpected and hard to trace side effects. Read more about [functional programming](https://hackernoon.com/learn-functional-python-in-10-minutes-to-2d1651dece6f) and [immutability in Python](https://www.pythonforthelab.com/blog/mutable-and-immutable-objects/).

If you do wish to "update" the same object, assign the result to the same variable:

In [533]:
students = students.dropna()

Some functions also offer the `inplace` option:

In [534]:
students.dropna(inplace=True)  # equivalent to above

/Users/stefan/.virtualenvs/viz-workshop/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


### Dataframe Operations

Array-wise functions and operations are naturally extended to dataframes

**ℹ️ Tip**: a dataframe is composed by multiple `pd.Series`. Each column can be a series, and each row can be a series. A series is a "labeled list" — where each `value` has an `index`.

In [535]:
students  # contents refresher

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51      True  21.0    False          14    chocolate
b     182      57      True  19.0     True          78      vanilla
c     175      56     False  22.0     True          23   strawberry
d     185      85      True  23.0     True          62   strawberry
e     153      83      True  18.0    False          28      vanilla
x     170      70      True  23.0    False          80   strawberry

#### Arithmetic

In [536]:
students.weight - 10  # if only losing weight was this easy 😅

a    41
b    47
c    46
d    75
e    73
x    60
Name: weight, dtype: int64

In [537]:
students.height + students.weight  # note that the resulting series still has the same indices

a    209
b    239
c    231
d    270
e    236
x    240
dtype: int64

In [538]:
students.sum()

height                                                       1023
weight                                                        402
graduated                                                       5
age                                                           126
can_ride                                                        3
fav_number                                                    285
fav_icecream    chocolatevanillastrawberrystrawberryvanillastr...
dtype: object

In [539]:
students.mean()

height        170.500000
weight         67.000000
graduated       0.833333
age            21.000000
can_ride        0.500000
fav_number     47.500000
dtype: float64

**ℹ️ Tip**: The sum of the boolean series `graduated` is the number of people that graduated. The mean of `graduated` is the sum divided by the total number of students, which is precisely the percentage of students that graduated.

Most operations accept an `axis` argument, which can either be `0` (column-wise, default), or `1` (row-wise):

In [540]:
students.mean(axis=1)  # the average for each student, of their height, weight and graduation status.. which doesn't make much sense

a    61.00
b    84.00
c    69.00
d    88.75
e    70.50
x    85.75
dtype: float64

#### Logical

In [541]:
students.age > 21

a    False
b    False
c     True
d     True
e    False
x     True
Name: age, dtype: bool

In [542]:
students.graduated & ~students.can_ride  # students who graduated but cannot ride

a     True
b     True
c    False
d     True
e     True
x     True
dtype: bool

In [543]:
students.graduated.any()

True

In [544]:
students.graduated.all()

False

In [545]:
students == 21

height  weight  graduated    age  can_ride  fav_number  fav_icecream
a   False   False      False   True     False       False         False
b   False   False      False  False     False       False         False
c   False   False      False  False     False       False         False
d   False   False      False  False     False       False         False
e   False   False      False  False     False       False         False
x   False   False      False  False     False       False         False

#### String Functions

The raw string values of textual variables can be accessed with `.str`:

In [568]:
students.fav_icecream

a     chocolate
b       vanilla
c    strawberry
d    strawberry
e       vanilla
x    strawberry
Name: fav_icecream, dtype: object

In [571]:
students.fav_icecream.str.title()

a     Chocolate
b       Vanilla
c    Strawberry
d    Strawberry
e       Vanilla
x    Strawberry
Name: fav_icecream, dtype: object

In [574]:
students.fav_icecream.str.replace('straw', 'banned-')

a       chocolate
b         vanilla
c    banned-berry
d    banned-berry
e         vanilla
x    banned-berry
Name: fav_icecream, dtype: object

#### Arbitrary Functions

In [557]:
students.height.apply(lambda w: (w // 10) * 10)  # apply to each element of a column

a    150
b    180
c    170
d    180
e    150
x    170
Name: height, dtype: int64

In [558]:
students.apply(lambda row: row.height + row.weight, axis=1)  # apply row-wise

a    209
b    239
c    231
d    270
e    236
x    240
dtype: int64

In [559]:
def relabel_boolean(x):
    # if the argument is not a boolean, leave it as it is
    if type(x) is not bool:
        return x
    return 'yes' if x is True else 'no'

In [560]:
students.applymap(relabel_boolean)  # apply element-wise

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51       yes  21.0       no          14    chocolate
b     182      57       yes  19.0      yes          78      vanilla
c     175      56        no  22.0      yes          23   strawberry
d     185      85       yes  23.0      yes          62   strawberry
e     153      83       yes  18.0       no          28      vanilla
x     170      70       yes  23.0       no          80   strawberry

#### Statistical

One of the most useful shortcuts is `describe`, which quickly provides a list of descriptive statistics about each numeric column:

In [561]:
students.describe().round(2)

height  weight    age  fav_number
count    6.00    6.00   6.00        6.00
mean   170.50   67.00  21.00       47.50
std     12.85   14.60   2.10       29.32
min    153.00   51.00  18.00       14.00
25%    161.00   56.25  19.50       24.25
50%    172.50   63.50  21.50       45.00
75%    180.25   79.75  22.75       74.00
max    185.00   85.00  23.00       80.00

90% of the values are lower than the 90th percentile. This can be used for outlier detection, which will be explored in workshop 4.

In [562]:
students.describe(percentiles=[.1, .5, .9, .95]).round(3)

height  weight     age  fav_number
count    6.000   6.000   6.000       6.000
mean   170.500  67.000  21.000      47.500
std     12.849  14.601   2.098      29.324
min    153.000  51.000  18.000      14.000
10%    155.500  53.500  18.500      18.500
50%    172.500  63.500  21.500      45.000
90%    183.500  84.000  23.000      79.000
95%    184.250  84.500  23.000      79.500
max    185.000  85.000  23.000      80.000

---

Categorical variables aggregations:

In [565]:
students.fav_icecream.value_counts()

strawberry    3
vanilla       2
chocolate     1
Name: fav_icecream, dtype: int64

In [566]:
students.fav_icecream.unique()

array(['chocolate', 'vanilla', 'strawberry'], dtype=object)

In [567]:
students.fav_icecream.nunique()  # when you need just the amount of unique items, not their actual values

3

---

Two variables have high _pair-wise correlation_ (Pearson) when one is dependent on the other: there is a linear relationship between the two:

In [577]:
students.corr()

height    weight       age  fav_number
height      1.000000  0.015990  0.460068    0.634043
weight      0.015990  1.000000  0.019590    0.255505
age         0.460068  0.019590  1.000000    0.217848
fav_number  0.634043  0.255505  0.217848    1.000000

Two variables have high _covariance_ when they then to show similar behavior: greater values in one correspond to greater values in the other:

In [583]:
students.cov()

height  weight   age  fav_number
height       165.1     3.0  12.4       238.9
weight         3.0   213.2   0.6       109.4
age           12.4     0.6   4.4        13.4
fav_number   238.9   109.4  13.4       859.9

Positive _skewness_ indicates left-leaning distributions:

In [578]:
students.age.skew()

-0.5850793161279771

Positive _kurtosis_ indicates that the distribution has heavy tails and sharp peaks:

In [579]:
students.age.kurt()

-1.5495867768595044

Read more about [distribution measures](https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/basic-statistics/inference/supporting-topics/data-concepts/how-skewness-and-kurtosis-affect-your-distribution/).

#### Ordering

Sort by the index:

In [554]:
students.sort_index()

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51      True  21.0    False          14    chocolate
b     182      57      True  19.0     True          78      vanilla
c     175      56     False  22.0     True          23   strawberry
d     185      85      True  23.0     True          62   strawberry
e     153      83      True  18.0    False          28      vanilla
x     170      70      True  23.0    False          80   strawberry

Sort by (a combination of) column(s):

In [555]:
students.sort_values(by=['fav_number', 'age'])

height  weight graduated   age can_ride  fav_number fav_icecream
a     158      51      True  21.0    False          14    chocolate
c     175      56     False  22.0     True          23   strawberry
e     153      83      True  18.0    False          28      vanilla
d     185      85      True  23.0     True          62   strawberry
b     182      57      True  19.0     True          78      vanilla
x     170      70      True  23.0    False          80   strawberry

Compute each row's rank (average ranks in case of equality):

In [556]:
students.fav_number.rank()

a    1.0
b    5.0
c    2.0
d    4.0
e    3.0
x    6.0
Name: fav_number, dtype: float64

### Data Transformations

Restructuring operations. Same data, but different view, more fitted for the downstream task.

Transpose rows and columns (keeping labels):

In [580]:
students.T

a        b           c           d        e           x
height              158      182         175         185      153         170
weight               51       57          56          85       83          70
graduated          True     True       False        True     True        True
age                  21       19          22          23       18          23
can_ride          False     True        True        True    False       False
fav_number           14       78          23          62       28          80
fav_icecream  chocolate  vanilla  strawberry  strawberry  vanilla  strawberry

Transform a categorical variable into dummy variables:

In [582]:
pd.get_dummies(students.fav_icecream)

chocolate  strawberry  vanilla
a          1           0        0
b          0           0        1
c          0           1        0
d          0           1        0
e          0           0        1
x          0           1        0

### Group By

_Grouping_ puts together rows according to the values for a certain variable:

In [436]:
# exemplify on a new dataframe
performance = pd.DataFrame([
    ('Alice', 'CS 101', 4.0),
    ('Alice', 'CS 102', 3.0),
    ('Alice', 'EE 201', 4.0),
    ('Bob',   'CS 101', 3.0),
    ('Bob',   'EE 201', 4.0),
], columns=['student', 'class', 'grade'])

In [437]:
performance

student   class  grade
0   Alice  CS 101    4.0
1   Alice  CS 102    3.0
2   Alice  EE 201    4.0
3     Bob  CS 101    3.0
4     Bob  EE 201    4.0

In order to see the effects of grouping, we apply an aggregation on all the rows for each student:

In [439]:
performance.groupby('student').grade.mean()

student
Alice    3.666667
Bob      3.500000
Name: grade, dtype: float64

---

Group by multiple variables:

In [121]:
students.groupby(['graduated', 'fav_icecream']).age.mean()

graduated  fav_icecream
False      chocolate       23.0
           strawberry      20.0
           vanilla         20.0
True       chocolate       22.0
           strawberry      20.0
Name: age, dtype: float64

---

Iterate over the `groupby` object, feature value (student name here) and the rows for that value:

In [442]:
for student, classes in performance.groupby('student'):
    print(student, 'took', len(classes), 'classes, with an average of', classes.grade.mean().round(2))

Alice took 3 classes, with an average of 3.67
Bob took 2 classes, with an average of 3.5


### Pivot

_Pivoting_ "flips" the data according and applies an function. Select a discrete variable for the columns, one for the rows, and you get the unique values for each. Each observations in the original dataframe, falls into one such value intersection. Pick an aggregation to apply to that set of observations.

For example, if want to know the average `height` and `weight` for those students that `graduated` and those that did not:

In [431]:
pd.pivot_table(
    students,
    index='graduated',
    values=['height', 'weight'],
    aggfunc='mean',
)

height  weight
graduated                
False      161.75   83.25
True       182.50   61.50

Or the maximum `height` and `weight` instead:

In [112]:
pd.pivot_table(
    students,
    index='graduated',
    values=['height', 'weight'],
    aggfunc='max',
)

height  weight
graduated                
False         198      88
True          170      83

---

A special case of pivoting is _cross tabulation_, which returns the counts at each feature value intersection:

In [429]:
pd.crosstab(students.fav_icecream, students.graduated, margins=True)

graduated     False  True  All
fav_icecream                  
chocolate         3     1    4
strawberry        1     1    2
All               4     2    6

### Melt

_Melting_ can be thought of as the reverse of pivoting.

In [445]:
# exemplify on a new dataframe
height_evolution = pd.DataFrame({
    'Alice': np.linspace(160, 190, num=5),
    'Bob':   np.linspace(170, 180, num=5),
    'year':  range(2000, 2005),
})

In [446]:
height_evolution

Alice    Bob  year
0  160.0  170.0  2000
1  167.5  172.5  2001
2  175.0  175.0  2002
3  182.5  177.5  2003
4  190.0  180.0  2004

Currently, each student has their own column. But that is the same type of information. So, we can melt them into a single `student` column:

In [451]:
melted = height_evolution.melt(
    id_vars='year',
    value_vars=['Alice', 'Bob'],

    var_name='student',
    value_name='height',
)
melted

year student  height
0  2000   Alice   160.0
1  2001   Alice   167.5
2  2002   Alice   175.0
3  2003   Alice   182.5
4  2004   Alice   190.0
5  2000     Bob   170.0
6  2001     Bob   172.5
7  2002     Bob   175.0
8  2003     Bob   177.5
9  2004     Bob   180.0

### Join

_Joining_ combines two tables, based on a common variable

In [460]:
height_stats = height_evolution.describe().T[['min', 'max']].rename(columns=lambda c: c + '_height')
height_stats

min_height  max_height
Alice       160.0       190.0
Bob         170.0       180.0
year       2000.0      2004.0

_Note_: since these are column-wise statistics, we also get the smallest and largest values for `year`.

Both tables have the `student` column, which is the one we join on. For every row where `student` is `"Alice"`, combine the information from the `performance` dataframe (`class` and `grade`) with the information from the the other dataframe (`min_height` and `max_height`).

In [461]:
performance.join(height_stats, on='student')

student   class  grade  min_height  max_height
0   Alice  CS 101    4.0       160.0       190.0
1   Alice  CS 102    3.0       160.0       190.0
2   Alice  EE 201    4.0       160.0       190.0
3     Bob  CS 101    3.0       170.0       180.0
4     Bob  EE 201    4.0       170.0       180.0

_Note_: since `year` is not among `performance.student` values, the default left join ignores that entry. Learn more about [join types](http://www.sql-join.com/sql-join-types/).

### Time Series

In [597]:
from datetime import datetime

In [594]:
# number of pages read for the first week of classes
pages_read = pd.DataFrame({
    'Alice': np.random.randint(0, 50, size=7),
    'Bob':   np.random.randint(0, 20, size=7),
    'date': pd.date_range('7 Jan 2019', periods=7)
})

pages_read

Alice  Bob       date
0     47    7 2019-01-07
1     21   13 2019-01-08
2     30    1 2019-01-09
3     20   16 2019-01-10
4     31    1 2019-01-11
5      6    7 2019-01-12
6     32    5 2019-01-13

Comparison operations can be done against a `datetime`-compatible object:

In [603]:
late_start = datetime(year=2019, month=1, day=10)  # it's not fair to start counting that early

In [604]:
pages_read[pages_read.date > late_start]

Alice  Bob       date
4     31    1 2019-01-11
5      6    7 2019-01-12
6     32    5 2019-01-13

While dates represent specific timepoints (of various granularity), the difference between two such objects is a _time delta_: a duration, not a date:

In [609]:
late_start - pages_read.date.iloc[0]

Timedelta('3 days 00:00:00')

It can be instantiated by parsing natural language:

In [612]:
pd.Timedelta('7 days 5 hours 3 minutes')

Timedelta('7 days 05:03:00')

Timedeltas can be used to offset date objects:

In [610]:
pages_read.date + pd.Timedelta(7, 'd')  # much better, a whole week later

0   2019-01-14
1   2019-01-15
2   2019-01-16
3   2019-01-17
4   2019-01-18
5   2019-01-19
6   2019-01-20
Name: date, dtype: datetime64[ns]

### Hierarchical Data

In [628]:
enrollment = pd.DataFrame({
    'level':    np.random.choice(['grad', 'undergrad', 'phd'], size=20),
    'school':   np.random.choice(['Viterbi', 'Price', 'Marshall', 'Dornsife'], size=20),
    'students': np.random.randint(200, 5_000, size=20),
    'faculty':  np.random.randint(50,  500,   size=20),
}).drop_duplicates(subset=['level', 'school'])

enrollment

level    school  students  faculty
0         phd     Price       270      189
2        grad  Dornsife      1631      374
3         phd  Dornsife      2359      132
4   undergrad  Marshall      1392      125
6   undergrad   Viterbi      3558      322
7   undergrad  Dornsife      2652      220
10        phd  Marshall      4565      327

In [629]:
enrollment.set_index(['school', 'level']).sort_index()

students  faculty
school   level                       
Dornsife grad           1631      374
         phd            2359      132
         undergrad      2652      220
Marshall phd            4565      327
         undergrad      1392      125
Price    phd             270      189
Viterbi  undergrad      3558      322

---

In [636]:
locations = pd.DataFrame({
    'Alice': ('San Francisco', 'CA', 'Los Angeles', 'CA'),
    'Bob':   ('Rochester', 'NY', 'Los Angeles', 'CA'),
    'Chris': ('Las Vegas', 'NV', 'Pennsylvania', 'PA'),
}).T

locations.columns = pd.MultiIndex.from_product([
    ['home', 'school'],
    ['city', 'state']
], names=['purpose', 'address'])

locations

purpose           home              school      
address           city state          city state
Alice    San Francisco    CA   Los Angeles    CA
Bob          Rochester    NY   Los Angeles    CA
Chris        Las Vegas    NV  Pennsylvania    PA

Read more about [advanced indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html)

### Loading Data

Data will almost always be loaded from an external source.

Load from JSON (open the file in the file browser to check out the source):

In [126]:
pd.read_json('example_files/objects.json')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

Load from CSV (again, the file is in the `example_files` folder):

In [127]:
pd.read_csv('example_files/tabular.csv')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

**ℹ️ Tip**: the CSV format is extremely common. There is a huge number of options available for loading such files. Read more about them [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

Load directly from an URL, letting Pandas do the downloading (paste that link into your browser to check the source):

In [462]:
pd.read_csv('https://raw.githubusercontent.com/stefan-niculae/viz-workshop/master/example_files/tabular.csv')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

Load directly from an archive, letting Pandas do the uncompressing (find the file and extract it in your local file browser to check the source):

In [463]:
pd.read_csv('example_files/archived.csv.zip')

grade   name  year
0   3.90  Alice     2
1   3.80    Bob     3
2   3.85  Chris     1

---

Saving data (check the result after running in the file browser):

In [130]:
performance.to_csv('students_performance.csv')

**ℹ️ Tip**: if the index is meaningless (e.g.: just the default sequential one), avoid wasting space and slightly encumbering the reading process by omitting it with `ignore_index=True`.

## Further Reading
 - Numpy: 
   - [cheatsheet](https://www.dataquest.io/blog/large_files/numpy-cheat-sheet.pdf)
   - [official quickstart guide](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html)
   - [official reference](https://docs.scipy.org/doc/numpy/reference/index.html#reference)
 - Scipy: [tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/index.html)
 - Pandas:
   - [visual cheatsheet](http://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
   - [cookbook](https://chrisalbon.com/#python)
   - [gotchas](https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#gotchas)
 - Python/Numpy/Scipy/Matplotlib: [quick tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 
Links to more details about particular concepts are placed at the end of their respective (sub)sections.